### ISSUE TITLE
ERROR - Cannot find animation frames for: shot, fire lion right, fire lion frong, snake right, icelance, ...

### ISSUE THREAD

**Issue by Murmele** [Tuxemon/Tuxemon#1185]
**Describe the bug**
During gameplay a few animations cannot be loaded

**To Reproduce**
1. Load save file: [slot2.zip](https://github.com/Tuxemon/Tuxemon/files/8692898/slot2.zip)
2. go to the right through through the trees
![image](https://user-images.githubusercontent.com/10099533/168425284-bd1e6857-c9be-4678-b42c-060a6e4314e2.png)

```
2022-05-14 13:49:13,974 - tuxemon.technique - ERROR - Cannot find animation frames for: shot
2022-05-14 13:49:14,004 - tuxemon.technique - ERROR - Cannot find animation frames for: fire lion right
2022-05-14 13:49:14,006 - tuxemon.technique - ERROR - Cannot find animation frames for: fire lion front
2022-05-14 13:49:14,028 - tuxemon.technique - ERROR - Cannot find animation frames for: snake right 64px
2022-05-14 13:49:14,045 - tuxemon.technique - ERROR - Cannot find animation frames for: icelance
2022-05-14 13:49:14,059 - tuxemon.technique - ERROR - Cannot find animation frames for: icelance
2022-05-14 13:49:14,078 - tuxemon.technique - ERROR - Cannot find animation frames for: fire lion right
2022-05-14 13:49:14,079 - tuxemon.technique - ERROR - Cannot find animation frames for: fire lion front
```

**Expected behavior**
Should find the animations

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Python Version 3.9

**Smartphone (please complete the following information):**
 - Device: Computer
 - OS: Linux

**Additional context**
Commit id: 4c5549fa3fcf48ed527631213f96d941c9376d8c

**Comment by bitcraft** [comment]
Missing animation frames might be able to be pulled from the wiki.  Some techniques have an animation specified, but they have not been created yet.  Sometimes the animation names don't match what is specified in the json.  For example, "fire lion front", probably refers to the animation "fire lion fron 64px".   The solution here would probably be best solved by renaming the file names, because "64px" in the name in non-conforming.  The other missing animations may be similar.
https://github.com/Tuxemon/Tuxemon/blob/development/mods/tuxemon/animations/technique/fire_lion_front_64px00.png

**Comment by kerizane** [comment]
I did some analysis of all our files. After running the animation download script the following items are still missing resources.

|Model Type|Name|Missing Resource|Note|
|-------------|--------------|-------------------|---|
|NpcModel|karrianna|maple_front.png|
|TechniqueModel|rust_bomb| puff|
|TechniqueModel|status_faint| None|
|TechniqueModel|glower| None|
|TechniqueModel|supernova| darkfire|
|TechniqueModel|flamethrower| fire lion right|
|TechniqueModel|invictus| triforce|
|TechniqueModel|menu_run| None|
|TechniqueModel|starfall| bolt|
|TechniqueModel|feint| bolt|
|TechniqueModel|biting_winds| ice blast|
|TechniqueModel|one_two| triple whammy|
|TechniqueModel|hibernate| None|
|TechniqueModel|fire_ball| darkfire|
|TechniqueModel|battery_discharge| disintegrate|
|TechniqueModel|overgrowth| None|
|TechniqueModel|levitate| None|
|TechniqueModel|sleeping_powder| dusty explosion|
|TechniqueModel|shadow_boxing| triple whammy|
|TechniqueModel|refresh| heal (no cross)|
|TechniqueModel|breathe_fire| fire lion right|
|TechniqueModel|snowstorm| ice blast|
|TechniqueModel|sand_spray| dusty explosion|
|TechniqueModel|sudden_glow| heal (no cross)|
|TechniqueModel|surge| bolt|
|TechniqueModel|salamander| fire enemy death 1|
|TechniqueModel|spray| None|
|TechniqueModel|swap| None|
|TechniqueModel|stampede| dusty explosion|
|TechniqueModel|whirlwind| whirlwind|
|TechniqueModel|static_field| disintegrate|
|TechniqueModel|battery_acid| disintegrate|
|TechniqueModel|avalanche| thud|
|MusicModel|music_gadget_store|488524_Purple---8-bit.ogg|
|MusicModel|music_sphalian_theme|Digital_Native.ogg|

**Summarised**
NPC:
maple_front.png

Technique:
bolt
darkfire
disintegrate
dusty explosion
fire enemy death 1
fire lion right
heal (no cross)
ice blast
puff
thud
triforce
triple whammy
whirlwind

Music:
Digital_Native.ogg
488524_Purple---8-bit.ogg

Some of these are present on the wiki but are the wrong size, they need to be 64x64.

**Comment by kerizane** [comment]
Missing animations I was able to download from the wiki as is:
https://github.com/Tuxemon/Tuxemon/pull/1232

**Comment by kerizane** [comment]
Digital Native is there, just looks like a typo. The other music file used to exist, need to figure out why it was removed.

`
        "slug" : "music_gadget_store",
        "file" : "488524_Purple---8-bit.ogg"
`
music_gadget_store is called by gadget_store1. There are no maps which lead to gadget_store1, and there weren't when it was created in https://github.com/Tuxemon/Tuxemon/pull/135. Maybe we should delete it?

The song was deleted in 24524d208f78d5d3821fdfb57552891ffcbc785a, because it's not a free asset. The website (https://www.newgrounds.com/audio/listen/488524) says: "Please contact me if you would like to use this in a project. We can discuss the details."

I will just delete the reference.

**Comment by Sanglorian** [comment]
For the animations larger than 64x64, ideally we'd change the part of the code that requires them to be that size rather than resize them

**Comment by kerizane** [comment]
I think we will need to define certain supported sizes and decide how we want them aligned.

We may want to allow the position of the animations to be configurable to some extent.

**Comment by Sanglorian** [comment]
My preference would be for animations of any size, centred on a particular point, as defined by an animation target specification: the user (0), the target (1), both (2) or in the middle of the screen (3). 

https://wiki.tuxemon.org/Property:TXMN_Animation_Target

But if it's only practical to have certain supported sizes, of course we can do that.

**Comment by AndyMender** [comment]
**EDIT:** Possible tasks discussed here: https://github.com/Tuxemon/Tuxemon/issues/1267#issuecomment-1232111217

However, it seems like the wiki is not accessible currently? I am getting timeouts both via browser and Python.

**Comment by kerizane** [comment]
@AndyMender Looks like the wiki is fixed now.

**Comment by AndyMender** [comment]
So the good news is that the updates to the animation download script I'm working on [here](https://github.com/Tuxemon/Tuxemon/pull/1285) will address the issue with downloading animations whose dimensions are not 64x64.

The bad news is that some animations have incorrect frame file names or records in the technique JSON files. I'll see if I can fix the ones mentioned in this ticket.

**Comment by AndyMender** [comment]
@Murmele could you confirm if this is now fixed with the latest development?

I no longer see the errors when I run your savegame file, however I see other errors:
```
pygame 2.1.2 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.2.8
Enabling logging of all modules.
2022-09-10 19:47:10,234 - tuxemon.rumble - ERROR - No rumble backends available.
2022-09-10 19:47:16,189 - tuxemon.event.actions.teleport_faint - ERROR - Teleport_faint action failed, because the teleport_faint variable has not been set.
2022-09-10 19:47:16,216 - tuxemon.event.actions.teleport_faint - ERROR - Teleport_faint action failed, because the teleport_faint variable has not been set.
2022-09-10 19:47:16,242 - tuxemon.event.actions.teleport_faint - ERROR - Teleport_faint action failed, because the teleport_faint variable has not been set.
2022-09-10 19:47:16,270 - tuxemon.event.actions.teleport_faint - ERROR - Teleport_faint action failed, because the teleport_faint variable has not been set.
2022-09-10 19:47:16,301 - tuxemon.event.actions.teleport_faint - ERROR - Teleport_faint action failed, because the teleport_faint variable has not been set.
2022-09-10 19:47:16,330 - tuxemon.event.actions.teleport_faint - ERROR - Teleport_faint action failed, because the teleport_faint variable has not been set.
2022-09-10 19:47:16,362 - tuxemon.event.actions.teleport_faint - ERROR - Teleport_faint action failed, because the teleport_faint variable has not been set.
2022-09-10 19:47:16,392 - tuxemon.event.actions.teleport_faint - ERROR - Teleport_faint action failed, because the teleport_faint variable has not been set.
2022-09-10 19:47:16,419 - tuxemon.event.actions.teleport_faint - ERROR - Teleport_faint action failed, because the teleport_faint variable has not been set.
2022-09-10 19:47:16,447 - tuxemon.event.actions.teleport_faint - ERROR - Teleport_faint action failed, because the teleport_faint variable has not been set.
2022-09-10 19:47:16,478 - tuxemon.event.actions.teleport_faint - ERROR - Teleport_faint action failed, because the teleport_faint variable has not been set
```
Could be that some of the events on the first spyder map don't correctly set the `teleport_faint` variable or an event was somehow skipped.

**Comment by kerizane** [comment]
Don't worry about teleport_faint, this is a new feature and we deliberately didn't add add logic for upgrading old save files.

**Comment by Murmele** [comment]
@AndyMender thank you for fixing. I will try it out

**Comment by Murmele** [comment]
In flatpak the config is stored for some unknown reason in:
/home/$USER/.var/app/org.tuxemon.Tuxemon/.tuxemon/

**Comment by kerizane** [comment]
Is this related to the current issue? If not, then create a new one.

**Comment by Murmele** [comment]
No I just searched the path where I have to place the save file. For some reason it is not directly in /home/$USER/.tuxemon

**Comment by Murmele** [comment]
Don't see the errors anymore
