### ISSUE TITLE
Tuxemon crashes while saving the game

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1760]
**Describe the bug**
This problem was encountered by my friend @cooollsaf who uses the latest development branch of Tuxemon and crashed while trying to save
**To Reproduce**
Enter the game with the Spyder version (we haven't tried if the Xero version crashes), then try to save the game and the game crashes

**Expected behavior**
The game should not crash, and it should save as normal
**Screenshots**
![1196ca3cfd37bbc3.png](https://user-images.githubusercontent.com/118408976/232264641-9a78057f-e042-4e24-b322-0e1a545f814f.png)
**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Python Version 3.10.6

**Smartphone (please complete the following information):**
 - Device: N/A

**Additional context**
I tested it on my computer and **it didn't have any problems**
(But I am using an older development version (2023/3/8) which I will test later with the latest development branch version)

**Comment by JaskRendix** [comment]
Tested on the latest (Linux) and it doesn't happen (no crash).

It happened before, but I fixed it here #1672. This was the cause: `the missing .hex was causing a crash when trying to save the game after a combat (wild encounter or trainer)`. Simply the game was crashing when trying to save **after** a fight.

The game crashes after fighting too? 
If it happens, well, then it could be the risk that the windows version isn't the latest or on windows they interpret JSON in a different way or something else.

**Comment by DavidLiang1129** [comment]
> Tested on the latest (Linux) and it doesn't happen (no crash).
> 
> It happened before, but I fixed it here #1672. This was the cause: `the missing .hex was causing a crash when trying to save the game after a combat (wild encounter or trainer)`. Simply the game was crashing when trying to save **after** a fight.
> 
> The game crashes after fighting too? 
> If it happens, well, then it could be the risk that the windows version isn't the latest or on windows they interpret JSON in a different way or something else.

Thanks, but my Windows version and Python version are even older than my friend's (I use Windows 7,Python 3.8) but nothing crashes, I wonder what's going on

**Comment by DavidLiang1129** [comment]
> Tested on the latest (Linux) and it doesn't happen (no crash).
> 
> It happened before, but I fixed it here #1672. This was the cause: `the missing .hex was causing a crash when trying to save the game after a combat (wild encounter or trainer)`. Simply the game was crashing when trying to save **after** a fight.
> 
> The game crashes after fighting too? 
> If it happens, well, then it could be the risk that the windows version isn't the latest or on windows they interpret JSON in a different way or something else.

Thanks, but my Windows version and Python version are even older than my friend's (I use Windows 7,Python 3.8) but nothing crashes, I wonder what's going on

**Comment by JaskRendix** [comment]
Is it still an issue?

**Comment by DavidLiang1129** [comment]
> Is it still an issue?

I think so, this is still a problem, although my friends and I still don't seem to know what the problem is, I asked some other friends, on their computers, still no problem, what the hell
(I'm sorry I probably shouldn't have used that word)

**Comment by DavidLiang1129** [comment]
> Is it still an issue?

By the way, I had an error with Player.py when running Tuxemon using Python3.8. After I commented out the code that caused the crash, the game worked, but my friend @cooollsaf's error had nothing to do with Player.py

**Comment by DavidLiang1129** [comment]
> Is it still an issue?

I think the crash was just a fluke, so we're going to shut it down until more people report problems
