### ISSUE TITLE
Environment battle music not referenced by slug

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#638]
107525d329c06bcd8352f7c660af557b53b3314a implemented slugs for sounds and music, replacing cases where audio files had to be called directly by their path. However it missed the use case of environment battle music: If for instance you go to mods/tuxemon/db/environment/grass.json you still see `"battle_music":"JRPGCollection/ogg/JRPG_battle_loop.ogg"` instead of `"battle_music":"music_battle_jrpg_battle_loop"`

**Comment by MirceaKitsune** [comment]
@xirsoi Since you worked on the sound database, can I leave this one to you? I'm busy with other issues today and may not have time to correct this.

**Comment by xirsoi** [comment]
Didn't even know this was a thing. I can take care of this, shouldn't take more than a few minutes.

**Comment by bitcraft** [comment]
Not sure if this would have shown the issue or not, but the standard test before opening a PR should be playing a new game until cotton town.  This should test the map conditions, battle animations, sounds, music, etc.  Unfortunately we have basically no automatic test coverage, so this manual test is required for now.

**Comment by xirsoi** [comment]
I did, but my implementation was generous, simply returning the slug if a record wasn't found.

I figured this would be a permissive implementation until the direct file reference was completely removed. I should have implemented a deprecation warning when the slug wasn't found.

Also, the fix for this was accidentally included in my last PR, so this ticket is fixed.

**Comment by MirceaKitsune** [comment]
Battle music is still referenced by slug in the latest development branch. Will close this once the change is merged.

**Comment by xirsoi** [comment]
pr submitted

**Comment by MirceaKitsune** [comment]
A heads up: Current development branch crashes when starting up a random battle. Apparently the battle music in the environment db still isn't referenced by slug and gets treated as a full path causing an IO error as the file isn't found.

```
mircea@linux-qz0r:~/Games/Small/Python/Tuxemon/Tuxemon_GIT> python ./tuxemon.py -l 1
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Enabling logging of all modules.
Found joystick: "Wacom Bamboo 2FG 4x5 Pad"
Configuring joystick: "Wacom Bamboo 2FG 4x5 Pad"
2020-02-06 06:10:10,343 - tuxemon.core.rumble - ERROR - No rumble backends available.
2020-02-06 06:10:10,377 - tuxemon.core.save - ERROR - [Errno 2] No such file or directory: u'/home/mircea/.tuxemon/saves/slot3.save'
Traceback (most recent call last):
  File "./tuxemon.py", line 62, in <module>
    main.main(load_slot=args.slot)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/main.py", line 106, in main
    control.main()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 250, in main
    update(clock_tick)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 298, in update
    self.event_engine.update(time_delta)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/event/eventengine.py", line 334, in update
    self.update_running_events(dt)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/event/eventengine.py", line 405, in update_running_events
    action.start()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/event/actions/random_encounter.py", line 99, in start
    mixer.music.load(tools.transform_resource_filename('music', filename))
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/tools.py", line 101, in transform_resource_filename
    return prepare.fetch(*filename)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/prepare.py", line 199, in fetch
    raise IOError(relative_path)
IOError: music/music_battle_loop
```

**Comment by xirsoi** [comment]
Fixed in a PR I opened a little bit ago.
